"""create analyses table

Revision ID: efd4dd0a45be
Revises: 
Create Date: 2026-09-23 19:58:40.352335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd4dd0a45be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protein_id', sa.String(length=255), nullable=True),
    sa.Column('protein_name', sa.String(length=255), nullable=True),
    sa.Column('organism', sa.String(length=255), nullable=True),
    sa.Column('accession', sa.String(length=100), nullable=True),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
